<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_NegativeTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3c938366-9a10-4a18-9c11-2b6151201f82</testSuiteGuid>
   <testCaseLink>
      <guid>7a009a37-83f7-4965-914f-15a56b3e6cc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7192dfd1-58de-41b8-9128-77871d4c7290</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ec6cbd-30c6-485a-aacc-59bc45f92256</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc054df0-4a41-428e-83a0-d2d1f60beed7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aad4a3d0-4e6e-4494-99c3-7b00a19ecb31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80029fa-d7f6-4515-9a1e-3cbe1f21361a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b181046f-2503-4ab1-b306-b7b983604061</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36adbd74-131c-445d-94d1-5f5c991751d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9c92f76-8ed9-4561-9e2b-dc03263755c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10f07642-580b-4331-b93f-284b08c8656b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f83bba-284a-4aa1-96d5-b73fac64b511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfd85c66-5188-4bae-aab9-d91b433ca9be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91a6452d-7f44-4b4f-97bf-e9493e12fac5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>484e432e-1b76-4c51-8ea3-c695a12e82aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>494e1db8-e58a-4ab9-94fb-23ff98713086</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b31e3d2-f4c1-44a9-8051-f42c1190ac4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c7d8516-b259-46f1-ac27-17c9c8e54648</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26e2ed0-601f-413f-a11f-dadbd8f53411</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17f99e26-61b9-4e6b-acac-0767753fa554</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetSingleUser_Fail_NotFound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fcf6685-dd6e-41a1-90f6-3ebc7b9e42b2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
