<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_RegressionTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>be24822e-20e8-4636-99fe-2821fd18ade9</testSuiteGuid>
   <testCaseLink>
      <guid>76bd47d6-b3b5-4aa7-9ffd-42ff084117c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e932f8a-69be-4ab0-9ec2-42d1b6372863</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64fd85c5-938c-4333-a78d-48689edf1109</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>961a8b87-02f5-4c0f-b00f-ca113e5da0cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7192dfd1-58de-41b8-9128-77871d4c7290</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ec6cbd-30c6-485a-aacc-59bc45f92256</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55706a2e-3f95-421c-be0f-a7543a373a2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aad4a3d0-4e6e-4494-99c3-7b00a19ecb31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80029fa-d7f6-4515-9a1e-3cbe1f21361a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf6a515b-939d-4c20-bd00-44b56afc3c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Fail_MissingPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36adbd74-131c-445d-94d1-5f5c991751d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9c92f76-8ed9-4561-9e2b-dc03263755c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>500aefa9-6210-4492-b0c7-6aa0d592ea08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bde475a-188f-46d1-8537-5bb6ccbc5f87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba505193-c85c-4276-96f0-8dc7d72be1db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>139c2ffa-11c3-4560-a3b5-3e75c9e0ebba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f83bba-284a-4aa1-96d5-b73fac64b511</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfd85c66-5188-4bae-aab9-d91b433ca9be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1ac60f9-a86f-4b0d-9f25-a3a00b16a4a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>484e432e-1b76-4c51-8ea3-c695a12e82aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>494e1db8-e58a-4ab9-94fb-23ff98713086</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8058ed6a-98a1-4277-bfe1-af09d0ca867f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Fail_MissingPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c7d8516-b259-46f1-ac27-17c9c8e54648</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26e2ed0-601f-413f-a11f-dadbd8f53411</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05da862f-a21f-472b-bc8d-d60f230f0b68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetListUsers</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b255da40-175d-433b-bac2-03bc92dd30a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16291ccd-2025-43e8-9821-29bbe69b11f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetSingleUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe71f7f-f350-4020-ada3-9b10e9246a73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23236505-5baa-4e4c-ae82-79f5712cb68c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetSingleUser_Fail_NotFound</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fcf6685-dd6e-41a1-90f6-3ebc7b9e42b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a47d600e-94cb-4209-91dd-59badcd3c540</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/POST/TC_CreateUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1800b8e-66dd-415b-834b-801bfeed6f68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2cd8c9-5d24-4c96-a04c-9e5f7493bb88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7462515b-c15b-4108-9aec-7ab3b2338e23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/PUT/TC_UpdateUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f7a07e-54c9-4959-82cb-c1e0d0992292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28ff2acd-a698-41d6-b8a0-36fdefbfd482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5570f2fc-84e5-4a55-b333-20c37c5b5fdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3dd393c-57b1-4b44-adf5-04239a67c5c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/PATCH/TC_PartialUpdateUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc76d69-a509-4b22-91f7-ec943c7f3ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec1cedb8-7a56-449d-ad79-86b66a735d22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43d2d9f1-85dc-4ffd-865d-3636c711905b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/DELETE/TC_DeleteUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c8e5116-405e-42e5-9cbe-df3f0bdf8a07</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
