<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SmokeTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a7679d0f-6687-489f-993f-c1cea5168d10</testSuiteGuid>
   <testCaseLink>
      <guid>e8e72813-6804-4dee-876d-7a2163234caa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Register/TC_Register_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e932f8a-69be-4ab0-9ec2-42d1b6372863</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64fd85c5-938c-4333-a78d-48689edf1109</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>900f8620-2138-490d-a944-ae2c7a5984bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Auth/Login/TC_Login_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bde475a-188f-46d1-8537-5bb6ccbc5f87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba505193-c85c-4276-96f0-8dc7d72be1db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d060fd5-04d9-49e3-813a-f4dfe38c4fce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetListUsers</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b255da40-175d-433b-bac2-03bc92dd30a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f693cdb8-0a96-4410-b242-e3c483d8878d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/GET/TC_GetSingleUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe71f7f-f350-4020-ada3-9b10e9246a73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>962ca6fd-7b8d-4c3b-a71b-9ff413b8c518</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/POST/TC_CreateUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1800b8e-66dd-415b-834b-801bfeed6f68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a2cd8c9-5d24-4c96-a04c-9e5f7493bb88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fd9cb31-d124-4bc9-acbb-02786a1e7cea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/DELETE/TC_DeleteUser_Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c8e5116-405e-42e5-9cbe-df3f0bdf8a07</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
